### ISSUE TITLE
Suggestion: consider Keyring Social Importers

### ISSUE THREAD

**Issue by mdrovdahl** [WordPress/data-liberation#64]
Over the years, I've found https://github.com/beaulebens/keyring-social-importers to be a very effective tool for liberating content that I've created on proprietary platforms, such as Strava, Instapaper, Flickr, etc. Completing the (oftentimes OAuth) setup for each service can be a bit tricky, but the framework for services is fairly mature and might be worth considering for this project.

**Comment by jordesign** [comment]
This definitely looks interesting - especially for some of those more 'social media' type contents

**Comment by jordesign** [comment]
@mdrovdahl - I've reached out to @beaulebens and he expressed he is very open to this tool/plugin being worked on by the community - for the broader benefit of the WordPress community. I'm investigating how best we could do that - and mobilise contributions towards it.

**Comment by jordesign** [comment]
In fact - I've added it to our public tools to be highlighted here:
https://github.com/WordPress/data-liberation/tree/trunk/tools/keyring-importer

**Comment by mdrovdahl** [comment]
_Back after extended leave_. Sounds great. I'll close this now that you've got Keyring on your radar.
