### ISSUE TITLE
Tracking Issue: WordPress to WordPress migrations

### ISSUE THREAD

**Issue by jordesign** [WordPress/data-liberation#73]
As of June 2024 [WordPress to WordPress migrations are an important part of the Data Liberation project].(https://make.wordpress.org/core/2024/06/21/data-liberation-and-wordpress-migrations/) 

Plenty of third-party plugins assist with this kind of migration and are meeting user needs, but we should also improve the options within WordPress itself.

## How can I contribute?
You can add your voice to existing discussions (listed below)

* [Site Transfer Protocol (Trac)](https://core.trac.wordpress.org/ticket/60375)

**Comment by adamziel** [comment]
We could close this issue in favor of https://github.com/WordPress/wordpress-playground/issues/1894

**Comment by jordesign** [comment]
That plan works for me 👍. Closing in favour of https://github.com/WordPress/wordpress-playground/issues/1894,
